export const fallbackSettings = {
  locale: "tr",
  organizationName: "Tüketiciler Birliği",
  shortName: "Tüketiciler Birliği",
  description: "Kurum tanıtımı, ekip ve çalışma alanları için özgün metinler içerik ekibi tarafından hazırlanacaktır.",
  phone: "Telefon bilgisi eklenecek",
  email: "iletisim@ornek-domain.org",
  kep: "KEP adresi eklenecek",
  address: "Açık adres bilgisi eklenecek",
  workingHours: "Hafta içi çalışma saatleri eklenecek",
  mapQuery: "Ankara",
  socialLinks: {
    x: "",
    facebook: "",
    instagram: "",
    youtube: "",
  },
};

export const fallbackContents = [
  {
    id: 1,
    type: "guide",
    locale: "tr",
    title: "Ayıplı Mal ve Hizmet Başvuruları",
    slug: "ayipli-mal-ve-hizmet-basvurulari",
    summary: "Ayıplı mal veya hizmet nedeniyle başvuru yapmadan önce hangi belgelerin gerektiğini ve hangi hakların talep edilebileceğini özetler.",
    body: "Ayıplı mal ve hizmetlerde başvuru sürecine başlamadan önce tüketicinin seçimlik hakları, başvuru süreleri ve delil olarak kullanılabilecek belgeler bu rehberde açıklanır.",
    status: "published",
    is_featured: true,
    published_at: "2026-07-01T09:00:00.000Z",
  },
  {
    id: 2,
    type: "guide",
    locale: "tr",
    title: "Mesafeli Satışlarda Cayma Hakkı",
    slug: "mesafeli-satislarda-cayma-hakki",
    summary: "İnternetten yapılan alışverişlerde cayma süresi, istisnalar ve iade sürecinin nasıl işleyeceğini kısa başlıklarla anlatır.",
    body: "Mesafeli satış sözleşmelerinde cayma hakkının kapsamı, hangi ürünlerde istisna olduğu ve satıcıya bildirimin nasıl yapılacağı bu rehberde yer alır.",
    status: "published",
    is_featured: true,
    published_at: "2026-07-02T09:00:00.000Z",
  },
  {
    id: 3,
    type: "news",
    locale: "tr",
    title: "Tüketici Hakları Bilgilendirme İçerikleri Hazırlanıyor",
    slug: "tuketici-haklari-bilgilendirme-icerikleri-hazirlaniyor",
    summary: "Tüketicilerin en çok yönelttiği sorulara odaklanan yeni rehber ve açıklama içerikleri için editoryal hazırlık süreci başlatıldı.",
    body: "Hazırlanan yeni içerik seti; ayıplı mal, cayma hakkı, garanti ve başvuru süreçleri gibi konularda daha anlaşılır ve düzenli bilgilendirme sunmayı amaçlıyor.",
    status: "published",
    is_featured: true,
    published_at: "2026-07-10T09:00:00.000Z",
  },
  {
    id: 3.1,
    type: "news",
    locale: "tr",
    title: "Başvuru Sürecini Kolaylaştıran Yeni İçerik Serisi Yayına Alınacak",
    slug: "basvuru-surecini-kolaylastiran-yeni-icerik-serisi-yayina-alinacak",
    summary: "Başvuru adımları, gerekli belgeler ve sık yapılan hatalar için sade anlatımlı yeni içerik serisinin yayına alınması planlanıyor.",
    body: "Yeni içerik serisi; başvuru öncesi hazırlık, belge kontrolü, tüketici haklarının temel çerçevesi ve örnek süreç akışları gibi başlıklarla ziyaretçilerin doğru bilgiye daha hızlı ulaşmasını hedefliyor.",
    status: "published",
    is_featured: false,
    published_at: "2026-07-16T09:00:00.000Z",
  },
  {
    id: 4,
    type: "announcement",
    locale: "tr",
    title: "İletişim Kanalları Güncellenecek",
    slug: "iletisim-kanallari-guncellenecek",
    summary: "Telefon, e-posta ve adres bilgileri yeni dönem iletişim planına göre güncellenerek siteye eklenecek.",
    body: "Başvuru ve bilgilendirme süreçlerinde ziyaretçilerin kuruma daha hızlı ulaşabilmesi için iletişim bilgileri gözden geçirilerek tek bir merkezde toplanacak.",
    status: "published",
    is_featured: true,
    published_at: "2026-07-12T09:00:00.000Z",
  },
  {
    id: 5,
    type: "faq",
    locale: "tr",
    title: "Tüketici başvurusu yapmak için üye olmak gerekir mi?",
    slug: "tuketici-basvurusu-yapmak-icin-uye-olmak-gerekir-mi",
    summary: "Başvuru",
    body: "Ön başvuru formunu doldurmak için üye olmanız gerekmez. Başvurunuz incelendikten sonra ekibimiz gerekli görülürse ek bilgi, belge veya üyelik süreci hakkında sizinle iletişime geçer.",
    status: "published",
    is_featured: false,
    published_at: "2026-07-12T09:00:00.000Z",
  },
  {
    id: 6,
    type: "faq",
    locale: "tr",
    title: "Başvuru için ücret ödenir mi?",
    slug: "basvuru-icin-ucret-odenir-mi",
    summary: "Başvuru",
    body: "Ön başvuru göndermek için herhangi bir ödeme alınmaz. Olası resmi başvuru, harç veya ek işlem gereklilikleri konuya göre ayrıca değerlendirilir ve size açık şekilde bildirilir.",
    status: "published",
    is_featured: false,
    published_at: "2026-07-12T09:00:00.000Z",
  },
  {
    id: 7,
    type: "faq",
    locale: "tr",
    title: "Başvuruda hangi belgeleri paylaşmalıyım?",
    slug: "basvuruda-hangi-belgeleri-paylasmaliyim",
    summary: "Belgeler",
    body: "Fatura, fiş, sözleşme, garanti belgesi, servis formu, kargo kaydı ve satıcıyla yapılan yazışmalar başvurunun daha hızlı değerlendirilmesine yardımcı olur. Elinizdeki belgeleri okunaklı şekilde yüklemeniz yeterlidir.",
    status: "published",
    is_featured: false,
    published_at: "2026-07-12T09:00:00.000Z",
  },
  {
    id: 8,
    type: "faq",
    locale: "tr",
    title: "Başvuruma ne kadar sürede dönüş yapılır?",
    slug: "basvuruma-ne-kadar-surede-donus-yapilir",
    summary: "Süreç",
    body: "Başvurular geliş sırasına ve konunun kapsamına göre incelenir. Eksik bilgi yoksa ekip en kısa sürede sizinle iletişime geçer; ek belge gerekiyorsa süreç hakkında ayrıca bilgilendirme yapılır.",
    status: "published",
    is_featured: false,
    published_at: "2026-07-12T09:00:00.000Z",
  },
  {
    id: 9,
    type: "faq",
    locale: "tr",
    title: "Ayıplı mal veya hizmette ilk olarak ne yapmalıyım?",
    slug: "ayipli-mal-veya-hizmette-ilk-olarak-ne-yapmaliyim",
    summary: "Haklar",
    body: "Öncelikle satın alma belgenizi ve yaşadığınız sorunu gösteren kayıtları saklayın. Satıcı veya sağlayıcıya yazılı başvuru yapmanız, sonraki değerlendirme ve resmi süreçlerde delil niteliği taşıyabilir.",
    status: "published",
    is_featured: false,
    published_at: "2026-07-12T09:00:00.000Z",
  },
  {
    id: 10,
    type: "faq",
    locale: "tr",
    title: "E-ticaret alışverişlerinde cayma hakkımı nasıl kullanırım?",
    slug: "e-ticaret-alisverislerinde-cayma-hakkimi-nasil-kullanirim",
    summary: "Haklar",
    body: "Mesafeli satışlarda cayma hakkı, ürün ve hizmet türüne göre değişebilen istisnalara tabidir. Satıcıya süresi içinde yazılı bildirim yapmanız ve iade koşullarını belgeleyerek ilerlemeniz önerilir.",
    status: "published",
    is_featured: false,
    published_at: "2026-07-12T09:00:00.000Z",
  },
  {
    id: 11,
    type: "faq",
    locale: "tr",
    title: "Başvuru yaptıktan sonra bilgilerimi güncelleyebilir miyim?",
    slug: "basvuru-yaptiktan-sonra-bilgilerimi-guncelleyebilir-miyim",
    summary: "Süreç",
    body: "Başvurunuzla ilgili ek belge veya açıklama paylaşmanız gerekiyorsa iletişim kanallarımızdan bize ulaşabilirsiniz. Ekibimiz başvuru kaydınızı güncellemeniz için sizi doğru kanala yönlendirir.",
    status: "published",
    is_featured: false,
    published_at: "2026-07-12T09:00:00.000Z",
  },
  {
    id: 12,
    type: "faq",
    locale: "tr",
    title: "Kişisel verilerim nasıl korunur?",
    slug: "kisisel-verilerim-nasil-korunur",
    summary: "Gizlilik",
    body: "Başvuru ve iletişim süreçlerinde paylaştığınız kişisel veriler yalnızca ilgili talebin değerlendirilmesi, sizinle iletişim kurulması ve yasal yükümlülüklerin yerine getirilmesi amacıyla işlenir.",
    status: "published",
    is_featured: false,
    published_at: "2026-07-12T09:00:00.000Z",
  },
  {
    id: 13,
    type: "news",
    locale: "en",
    title: "Consumer Rights Information Content Is Being Prepared",
    slug: "consumer-rights-information-content-is-being-prepared",
    summary: "An editorial content series focused on the questions visitors ask most is being prepared for the website.",
    body: "The planned content set aims to provide clearer guidance on defective goods, withdrawal rights, warranty topics, and application steps with simpler editorial structure.",
    status: "published",
    is_featured: true,
    published_at: "2026-07-10T09:00:00.000Z",
  },
  {
    id: 13.1,
    type: "news",
    locale: "en",
    title: "A New Content Series To Simplify The Application Journey Will Be Published",
    slug: "a-new-content-series-to-simplify-the-application-journey-will-be-published",
    summary: "A new content series will cover application steps, required documents, and common mistakes in a simpler format.",
    body: "The upcoming series is designed to help visitors prepare before applying, understand document requirements, and follow the process more confidently.",
    status: "published",
    is_featured: false,
    published_at: "2026-07-16T09:00:00.000Z",
  },
  {
    id: 14,
    type: "faq",
    locale: "en",
    title: "Do I need to be a member to submit a consumer application?",
    slug: "do-i-need-to-be-a-member-to-submit-a-consumer-application",
    summary: "Application",
    body: "You do not need to be a member to submit the preliminary application form. After review, our team may contact you for additional information, documents, or membership-related guidance if needed.",
    status: "published",
    is_featured: false,
    published_at: "2026-07-12T09:00:00.000Z",
  },
  {
    id: 15,
    type: "faq",
    locale: "en",
    title: "Is there a fee for submitting an application?",
    slug: "is-there-a-fee-for-submitting-an-application",
    summary: "Application",
    body: "No payment is required to send a preliminary application. Any official application, fee, or additional procedural requirement is assessed according to the case and explained to you clearly.",
    status: "published",
    is_featured: false,
    published_at: "2026-07-12T09:00:00.000Z",
  },
  {
    id: 16,
    type: "faq",
    locale: "en",
    title: "Which documents should I share with my application?",
    slug: "which-documents-should-i-share-with-my-application",
    summary: "Documents",
    body: "Invoices, receipts, contracts, warranty documents, service forms, shipping records, and correspondence with the seller help us review the issue faster. Uploading readable copies of the documents you have is enough.",
    status: "published",
    is_featured: false,
    published_at: "2026-07-12T09:00:00.000Z",
  },
  {
    id: 17,
    type: "faq",
    locale: "en",
    title: "How soon will I receive a response?",
    slug: "how-soon-will-i-receive-a-response",
    summary: "Process",
    body: "Applications are reviewed in order and according to the scope of the issue. If no information is missing, our team will contact you as soon as possible; if more documents are needed, you will be informed.",
    status: "published",
    is_featured: false,
    published_at: "2026-07-12T09:00:00.000Z",
  },
  {
    id: 18,
    type: "faq",
    locale: "en",
    title: "What should I do first for defective goods or services?",
    slug: "what-should-i-do-first-for-defective-goods-or-services",
    summary: "Rights",
    body: "Keep your purchase documents and records that show the issue. A written request to the seller or provider can be useful evidence for later review and official procedures.",
    status: "published",
    is_featured: false,
    published_at: "2026-07-12T09:00:00.000Z",
  },
  {
    id: 19,
    type: "faq",
    locale: "en",
    title: "How can I use my withdrawal right for online purchases?",
    slug: "how-can-i-use-my-withdrawal-right-for-online-purchases",
    summary: "Rights",
    body: "Withdrawal rights in distance sales may vary depending on the product or service and related exceptions. We recommend notifying the seller in writing within the legal period and documenting the return process.",
    status: "published",
    is_featured: false,
    published_at: "2026-07-12T09:00:00.000Z",
  },
  {
    id: 20,
    type: "faq",
    locale: "en",
    title: "Can I update my information after submitting an application?",
    slug: "can-i-update-my-information-after-submitting-an-application",
    summary: "Process",
    body: "If you need to provide additional documents or explanations, you can contact us through our communication channels. Our team will guide you to the correct channel for updating your application record.",
    status: "published",
    is_featured: false,
    published_at: "2026-07-12T09:00:00.000Z",
  },
  {
    id: 21,
    type: "faq",
    locale: "en",
    title: "How is my personal data protected?",
    slug: "how-is-my-personal-data-protected",
    summary: "Privacy",
    body: "Personal data shared during application and communication processes is processed only to evaluate the relevant request, contact you, and fulfil legal obligations.",
    status: "published",
    is_featured: false,
    published_at: "2026-07-12T09:00:00.000Z",
  },
];

const fallbackProvinceEntries = [
  {
    id: "fallback-province-1",
    locale: "tr",
    provinceCode: 6,
    provinceName: "Ankara",
    title: "Ankara'da tüketici hakları bilgilendirme çalışması",
    summary: "Başkentte tüketici başvuru yolları ve temel haklara yönelik bilgilendirme içeriği.",
    category: "news",
    categoryLabel: "Haber",
    linkLabel: "Habere git",
    linkHref: "/haberler/tuketici-haklari-bilgilendirme-icerikleri-hazirlaniyor",
    eventDate: "2026-07-10",
    status: "published",
    sortOrder: 0,
  },
  {
    id: "fallback-province-2",
    locale: "tr",
    provinceCode: 34,
    provinceName: "İstanbul",
    title: "İstanbul için ayıplı mal başvuru rehberi",
    summary: "Ayıplı mal ve hizmet süreçlerinde izlenecek adımlar için il bazlı rehber bağlantısı.",
    category: "guide",
    categoryLabel: "Rehber",
    linkLabel: "Rehbere git",
    linkHref: "/hak-rehberleri/ayipli-mal-ve-hizmet-basvurulari",
    eventDate: "2026-07-01",
    status: "published",
    sortOrder: 1,
  },
  {
    id: "fallback-province-2b",
    locale: "tr",
    provinceCode: 34,
    provinceName: "İstanbul",
    title: "İstanbul'da e-ticaret şikayetleri için hızlı başvuru notları",
    summary: "Mesafeli satış, iade süreci ve satıcıya bildirim adımları için kısa bilgilendirme kaydı.",
    category: "news",
    categoryLabel: "Haber",
    linkLabel: "Habere git",
    linkHref: "/haberler/tuketici-haklari-bilgilendirme-icerikleri-hazirlaniyor",
    eventDate: "2026-07-13",
    status: "published",
    sortOrder: 2,
  },
  {
    id: "fallback-province-2c",
    locale: "tr",
    provinceCode: 34,
    provinceName: "İstanbul",
    title: "İstanbul iletişim ve danışma kanalları güncellemesi",
    summary: "Başvuru öncesi kullanılabilecek iletişim hatları ve yönlendirme bilgileri.",
    category: "announcement",
    categoryLabel: "Duyuru",
    linkLabel: "Duyuruya git",
    linkHref: "/duyurular",
    eventDate: "2026-07-14",
    status: "published",
    sortOrder: 3,
  },
  {
    id: "fallback-province-3",
    locale: "tr",
    provinceCode: 35,
    provinceName: "İzmir",
    title: "İzmir'de mesafeli satışlarda cayma hakkı bilgilendirmesi",
    summary: "E-ticaret alışverişlerinde cayma hakkı ve iade sürecine dair özet içerik.",
    category: "guide",
    categoryLabel: "Rehber",
    linkLabel: "Rehbere git",
    linkHref: "/hak-rehberleri/mesafeli-satislarda-cayma-hakki",
    eventDate: "2026-07-02",
    status: "published",
    sortOrder: 4,
  },
  {
    id: "fallback-province-3b",
    locale: "tr",
    provinceCode: 35,
    provinceName: "İzmir",
    title: "İzmir'de abonelik iptali ve cayma hakkı rehberi",
    summary: "Dijital üyelikler ve uzaktan kurulan sözleşmeler için hak özeti.",
    category: "guide",
    categoryLabel: "Rehber",
    linkLabel: "Rehbere git",
    linkHref: "/hak-rehberleri/mesafeli-satislarda-cayma-hakki",
    eventDate: "2026-07-15",
    status: "published",
    sortOrder: 5,
  },
  {
    id: "fallback-province-3c",
    locale: "tr",
    provinceCode: 35,
    provinceName: "İzmir",
    title: "İzmir tüketici buluşmasında sık sorulan sorular paylaşıldı",
    summary: "Yerel bilgilendirme toplantısında öne çıkan başvuru sorularının özeti.",
    category: "activity",
    categoryLabel: "Faaliyet",
    linkLabel: "Habere git",
    linkHref: "/haberler/tuketici-haklari-bilgilendirme-icerikleri-hazirlaniyor",
    eventDate: "2026-07-16",
    status: "published",
    sortOrder: 6,
  },
  {
    id: "fallback-province-4",
    locale: "tr",
    provinceCode: 42,
    provinceName: "Konya",
    title: "Konya tüketici bilgilendirme buluşması",
    summary: "Tüketicilerin sık yaşadığı başvuru sorunlarına yönelik yerel bilgilendirme kaydı.",
    category: "activity",
    categoryLabel: "Faaliyet",
    linkLabel: "Habere git",
    linkHref: "/haberler/tuketici-haklari-bilgilendirme-icerikleri-hazirlaniyor",
    eventDate: "2026-07-12",
    status: "published",
    sortOrder: 7,
  },
  {
    id: "fallback-province-5",
    locale: "tr",
    provinceCode: 16,
    provinceName: "Bursa",
    title: "Bursa iletişim kanalları duyurusu",
    summary: "Başvuru ve iletişim kanallarının güncellenmesine dair duyuru bağlantısı.",
    category: "announcement",
    categoryLabel: "Duyuru",
    linkLabel: "Duyuruya git",
    linkHref: "/duyurular",
    eventDate: "2026-07-12",
    status: "published",
    sortOrder: 8,
  },
  {
    id: "fallback-province-1b",
    locale: "tr",
    provinceCode: 6,
    provinceName: "Ankara",
    title: "Ankara'da garanti kapsamı ve servis süreçleri duyurusu",
    summary: "Servis fişi, garanti belgesi ve teslim kayıtlarıyla ilgili örnek bilgilendirme.",
    category: "announcement",
    categoryLabel: "Duyuru",
    linkLabel: "Duyuruya git",
    linkHref: "/duyurular",
    eventDate: "2026-07-17",
    status: "published",
    sortOrder: 9,
  },
  {
    id: "fallback-province-1c",
    locale: "tr",
    provinceCode: 6,
    provinceName: "Ankara",
    title: "Ankara için tüketici başvuru belgeleri kontrol listesi",
    summary: "Başvuru öncesi hazırlanması gereken temel belgeleri özetleyen rehber kaydı.",
    category: "guide",
    categoryLabel: "Rehber",
    linkLabel: "Rehbere git",
    linkHref: "/hak-rehberleri/ayipli-mal-ve-hizmet-basvurulari",
    eventDate: "2026-07-18",
    status: "published",
    sortOrder: 10,
  },
];

export function getFallbackContent(type, locale = "tr") {
  return fallbackContents.filter((content) => content.type === type && content.locale === locale);
}

export function getFallbackHeroSlides(locale = "tr") {
  const isEnglish = locale === "en";

  return [
    {
      id: "fallback-hero-1",
      title: isEnglish ? "Consumer Rights Information Content Is Being Prepared" : "Tüketici Hakları Bilgilendirme İçerikleri Hazırlanıyor",
      summary: isEnglish
        ? "Sample hero content for the homepage. It should be replaced with real editorial copy from the admin panel."
        : "Ana sayfa için örnek hero içeriği. Yönetim panelinden gerçek editoryal içerikle güncellenmelidir.",
      ctaLabel: isEnglish ? "Read More" : "Devamını Oku",
      href: isEnglish ? "/news/tuketici-haklari-bilgilendirme-icerikleri-hazirlaniyor" : "/haberler/tuketici-haklari-bilgilendirme-icerikleri-hazirlaniyor",
      image: "/ornek-hero.png",
      imageMobile: "/ornek-hero.png",
      imageTablet: "/ornek-hero.png",
      imageDesktop: "/ornek-hero.png",
    },
    {
      id: "fallback-hero-2",
      title: isEnglish ? "Application Guidance Will Be Managed From The Admin Panel" : "Başvuru Rehberi İçeriği Yönetim Panelinden Yönetilecek",
      summary: isEnglish
        ? "Hero slides will become independently manageable with bilingual copy, image selection, and ordering."
        : "Hero slaytları çift dilli metin, görsel seçimi ve sıralama desteğiyle bağımsız olarak yönetilebilecek.",
      ctaLabel: isEnglish ? "Application Guide" : "Başvuru Rehberi",
      href: "/basvuru-rehberi",
      image: "/ornek-hero-2.png",
      imageMobile: "/ornek-hero-2.png",
      imageTablet: "/ornek-hero-2.png",
      imageDesktop: "/ornek-hero-2.png",
    },
  ];
}

export function getFallbackProvinceMap() {
  const provinces = Array.from({ length: 81 }, (_, index) => {
    const code = index + 1;
    const entries = fallbackProvinceEntries.filter((entry) => entry.provinceCode === code);
    const firstEntry = entries[0];

    return {
      code,
      name: firstEntry?.provinceName || "",
      count: entries.length,
      entries,
    };
  });

  const activeProvinceCount = provinces.filter((province) => province.count > 0).length;

  return {
    provinces,
    latestEntries: fallbackProvinceEntries.slice(0, 6),
    stats: {
      totalEntries: fallbackProvinceEntries.length,
      activeProvinceCount,
      categoryCounts: {
        news: 2,
        announcement: 3,
        guide: 4,
        activity: 2,
      },
    },
  };
}
